name: Build Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency: 
  group: build-Linux-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install flex

          wget https://ftp.gnu.org/gnu/bison/bison-3.7.6.tar.gz
          tar xvfz bison-3.7.6.tar.gz
          cd bison-3.7.6
          ./configure
          make 
          sudo make install

      - name: Build 
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeAppendedArgs: >-
            -DUNFOLDTACPN_TEST=OFF
          cmakeBuildType: Release
          cmakeGenerator: UnixMakefiles
          buildDirectory: '${{runner.workspace}}/build'